### ISSUE TITLE
ImportError: No module named 'fooof.synth.gen'; 'fooof.synth' is not a package

### ISSUE THREAD

**Issue by LeilaNS** [fooof-tools/fooof#125]
Hi,
I tried to run your exemple : plot_synth_params.py, but I got this error :

> ImportError: No module named 'fooof.synth.gen'; 'fooof.synth' is not a package.

I upgrade my fooof but it didn't fix the error, I can use the other fooof function and no error when I run import fooof
Thanks,

**Comment by TomDonoghue** [comment]
Hey Leila, 

Sorry - that is an organizational quirk from our end. We are preparing for a new release, with some code updates that are not yet released on PYPI, but the docsite is actually a little ahead. 

To run that example right now, you can install the current development version of FOOOF (instructions to do so in the README). Otherwise, the relevant changes there are, I think, having just moved some code (it's all still there), so it might work if you update all the imports like this:

```
# Import fooof functions for creating spectra and managing parameters
from fooof.synth import param_sampler, param_iter, Stepper
from fooof.synth import gen_power_spectrum, gen_group_power_spectra

# Import some fooof plotting functions
from fooof.plts import plot_spectrum, plot_spectra
```

Sorry things fell out of sync - that is our bad - but the new release should be out soon!

**Comment by LeilaNS** [comment]
Thanks
