### ISSUE TITLE
Review of Documentation Site

### ISSUE THREAD

**Issue by TomDonoghue** [fooof-tools/fooof#167]
This issue is for a review of the FOOOF documentation site, for the 1.0 pre-release. 

It is partly to manage the audit being done by @ryanhammonds, but anyone else is also welcome to contribute any comments, suggestions or fixes (though please let Ryan check off the boxes). 

To give some structure, I've tried to map out the things I would like to be checked, both from an organizational & conception standpoint, and checking through content, including copyediting. This doesn't have to be done in any particular order, and broadly this is partly just a list to try and make sure the check through goes through all the different pages. For anything that comes up - feel free to leave comments here, sends me notes & messages, and/or open PullRequests with direct fixes. Any thoughts / comments / ideas etc that are beyond or not directly related to what's listed below are also very welcome!

Organization & Logic:
- [x] Is the layout of the site good to use? Do the entries and order of the menu bar items at the top of the page make sense?
- [x] Is there a sensible entry point for potential new users? Is the README well organized as a landing page, and does it seem like it leads to where people might need to go? Alternatively put, can you think of any other useful guide or 'go here for X' that would be more useful?
- [x] Is there anything that seems like it's missing from the website? For example, any elements or pages that are typically on code documentation sites, but aren't including here? Is there anything you want to know, or do, but can't find guidance for on the website?
- [x] Are you able, based on the instructions on the site, to get the pre-release of FOOOF installed and working, and are able to use it (for example, in the pages you can download from tutorials, etc). 

Content & Functionality:
- [x] Does the `motivations` section offer a good and accessible entry point into motivating the model? Is there anything that was unclear, or felt like it was missing?
    - [x] Were you able to download each file, and run it locally
    - [x] Check through the section for typos & wording issues
- [x] Does the `tutorials` section offer a good and accessible guide through using the module? Is there anything that was unclear or seemed missing? Does it seem complete in a way to be able to start using the module after reading through the tutorials?
    - [x] Were you able to download each file, and run it locally
    - [x] Check through the section for typos & wording issues
- [x] Does the `examples` section offer a good and accessible overview of other functionality in the module? Does it seem reasonably organized to find particular function that one might want?
    - [x] Were you able to download each file, and run it locally
    - [x] Check through the section for typos & wording issues
- [x] Is the organization of the `API` page sensible? Do the headers and small descriptions 
    - [x] Are you able to successfully click through to each object / function and also subsequently through to each method (from an object page)?
    - [x] As you click through each page across the API, does everything seem to be rendered correctly? Are there any typos, or wording issues? As far as you can tell, are things documented consistently across different fucntions?
- [x] Does the `Glossary` page seem to include all the relevant terms related to the module? As far as you can tell, are the definitions and usages consistent with the rest of the module and site?
    - [x] Check through the section for typos & wording issues
- [x] Do the answers in the `FAQ` page seem understandable and useful? As far as you can tell, is the information in this section consistent with the rest of the module and site? Are there any questions that come to mind that could be added?
    - [x] Check through the section for typos & wording issues
- [x] Does the `README` page (landing page of the website) seem well organized and 
    - [x] Check through the section for typos & wording issues
- [x] Does the `reference` page offer instructions that seem clear and useful for citing the use of FOOOF? Does anything seem to be missing? Can you easily read this page, and generate the reports it mentions from FOOOF objects?
    - [x] Check through the section for typos & wording issues

**Comment by TomDonoghue** [comment]
@rdgao : if you get a chance to eyeball the new Tutorial #1, which I've updated to intersperse the math and the model with the annotated plots, that would be great! Thanks!

**Comment by ryanhammonds** [comment]
Thanks for organizing this and laying everything out for me! Working on this now.

**Comment by rdgao** [comment]
> @rdgao : if you get a chance to eyeball the new Tutorial-1, which I've updated to intersperse the math and the model with the annotated plots, that would be great! Thanks!

will do

**Comment by TomDonoghue** [comment]
I'm going to add in here some quick notes to myself (originally brought up by @nschawor), so that I remember to fold these things in as we do any updates here. 

Topic: `analysis.periodic` functions, where the the issue is about documenting and surfacing that there are basically two sets of function, the underlying utilities that operate on array, and wrapper functions that take in FOOOF objects.

To do items:
- [ ] Update tutorial number 8, which mismatches which functions it mentions and uses. Update the tutorial to consistently use the object based functions
- [ ] Check the docstrings for documentation, and update as needed (there is a misplaced comment in `get_band_peak_group`, that references fg objects). 
- [ ] Add more examples sections in these docstrings
- [ ] API listing: consider and update either the ordering or listing of these functions in the API page

**Comment by rdgao** [comment]
looks great, explanation is all clear and structure makes sense to me. Some specific edits/comments are listed below, but I think the one main issue is that the mathematical description of the model/variables are a bit inconsistent throughout the tutorial, like some letters are used in the same way regardless of linear- or log-power space.

What I'd do is to decide on a set of letters that you want to use to represent whatever, in either linear or log power, and then add the appropriate transforms in all the subsequent uses. For example, if you start with `P(f)` or `NPS(f)` is defined as the power spectrum, then `log10(NPS(f)) = L + sum(Gn)`, which then means `L = b - log(k+F^x)`, etc. Or you can start with P being the already logged spectrum, as it is defined in the paper right now I think.

---
some comments:
- as a tutorial (that can be as long as you want), I think it'd be helpful to show a plot of the spectrum without the fits first, just to orient people to what's the data and what's the model

> in power spectra, this looks like a line, or curve, across all frequencies
- is it a line or a curve? I think if you mean the general meaning of curve, like "curve-fitting", then no need to say it's a line, unless you mean very specifically that it's a straight line

- in the first mathematical description, I'm not sure if I would use the equation there, because it implicitly implies summation in linear power. I mean this is kind of a technicality, but you could just say NPS is a combination of aperiodic and periodic component without invoking the math in that first section.

- again, technicality, but I would say G(F)  = ... to make it clearer that F is the independent variable here. Same for L(F)

it says >Note that diagonal labels are unit-less measures (in neither units of frequency of power).
- what does diagonal mean? 

- in the mathematical description of aperiodic section, it says L = ...., then "equivalently, L = ... ": it's not really equivalent right? the second one should be logL = ...

- in the same section, I think by "exponential form" or "exponential function" you mean "Lorentzian form". It's exponential in time domain, and the frequency representation is Lorentzian.

- in relating exponent to power spectrum slope section, NPS is used to refer to the aperiodic component, where it was previously used to mean the whole power spectrum. I think you want to use logL here, still.

- I would end with a precise formulation of the model, like log(NPS) = L + sum(Gn)

**Comment by ryanhammonds** [comment]
I finished going through all of documentation and site. There were minor typos throughout that I fixed in #169. The content was clear and structured logically. Other than typos, there were a few minor things that I noted below.

- [x] Organization and Logic
    - Layout is logical. 
    - Readme points to everything a user would need that I can think of.
    - Nothing seems to be missing and the site offers more than other packages I’ve used.
    - Pre-release installable via pypi.

- [x] Motivations
    - This section was great. It clearly justifies why taking the time to learn how to use the package is important.
    - All notebooks downloaded and ran successfully.
    - Typos fixed.

- [x] Tutorials
    - After going through the tutorials, I could use the package. It also provides a good reference for when I forget how things work.
    - All notebooks downloaded and ran successfully.
    - Typos fixed.
    - plot_04-MoreFOOOF 
        - The last cell calling IFrame returns a 404 error on the site. It returns a grey box when running the notebook locally.
        - Looking into what is going on with this.

- [x] Examples
    - The examples were well organized and offered additional functionality that was not in tutorials, in addition to reinforcing usage/concepts introduced in the tutorials.
    - All notebooks downloaded and ran successfully.
    - Typos fixed.

- [x] API
    - API organization was logical and easy to follow.
    - All links worked.
    - Typos fixed.
    - fooof/data/data.py isn't loaded in the documentation properly.

- [x] Glossary
    - This covered all of the terms I wasn’t familiar with.
    - There was a small typo, but the glossary.rst in the master branch is not even with the glossary.html in the gh-pages branch.

- [x] FAQ
    - This section was useful and provided answers to questions I had and ones I didn’t know I had until reading.
    - Typos fixed.

- [x] Readme
    - This was well organized.
    - No typos found in this.

- [x] Reference
    - I think the one thing that could be added to this section is the actual citation, as is provided in the README reference section.
    - No typos found in this section.

**Comment by TomDonoghue** [comment]
@ryanhammonds : awesome, thanks for the thorough run through!

In terms of pulling out action items:
- [ ] Tutorials: iFrame in 04 
  - Note: well, this used to work. I can also have a look
- [ ] API: data objects don't generate well. Figure out a fix or strategy
  - I've gone back on forth on listing these in the API page, given the pages don't work well. I'm not sure what's best to do about listing them. 
- [ ] Glossary: fix typo
  - Note: oops, I forgot to push a couple small updates. Check the latest commit on master. Everything should be even with site now, so you can add any edits to the glossary file. 

Also, I have the tutorial things in the comments above, but otherwise, I think we're looking good here! Should I consider all the boxes in original comment can be clicked off (other than these last actions items here?).

**Comment by ryanhammonds** [comment]
No problem! I'll go back through the glossary today. Yes, the boxes in the original comment can be checked off. Everything looked great in terms of content and organization.

**Comment by TomDonoghue** [comment]
Okay, sounds good - whenever you have any typos or similar in the glossary, add it to the same PR, then I'll merge that. After, I can go from master to do the other things I want to update.

**Comment by TomDonoghue** [comment]
Merged in with #170
