### ISSUE TITLE
Error loading fooof tutorial data

### ISSUE THREAD

**Issue by elkosik** [fooof-tools/fooof#184]
Hi, I was doing the Module 2 in the fooof tutorial and copied and pasted the following lines of code:
```
from fooof import FOOOF
from fooof.utils.download import load_fooof_data
freqs = load_fooof_data('freqs.npy', folder='data')
```

After trying to load the "freqs" data, I got the following errors: 
- [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)
- URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>

Can you help me figure this out? Thanks!

**Comment by ryanhammonds** [comment]
Hi @elkosik, thanks for the issue! I think this may be a os or python version issue involving permissions when downloading from `https://raw.githubusercontent.com/fooof-tools/fooof/master/data/freqs.npy` using `urlretrieve`. What os and version of python are you using?

This [stackoverflow comment](https://stackoverflow.com/a/42334357) has a possible solution for macos users. However, I'm unable to test it since `load_fooof_data` doesn't raise the same error on my os.

If you run `git clone https://github.com/fooof-tools/fooof.git`, the tutorial data will be located inside of `fooof/data/freqs.npy`, and can be loaded using `freqs = np.load('fooof/data/freqs.npy')`. It can also be accessed here: https://github.com/fooof-tools/fooof/tree/master/data

**Comment by elkosik** [comment]
Solved with the stackoverflow suggestion. Thanks!
