### ISSUE TITLE
Fitting in Linear Space

### ISSUE THREAD

**Issue by ryanhammonds** [fooof-tools/fooof#186]
This issue is described here: https://github.com/rdgao/daily_notebook/blob/master/daily19_04_04_noisefloor.ipynb

In summary, when the aperiodic scale/sd becomes large, oscillations may be missed during the standard fitting procedure in semi-log space. A potential solution was described by @rdgao and my understanding is to remove the aperiodic fit in linear space (``spectrum  - 10**fm._ap_fit``). The fitting procedure after the ap_fit is removed may also need to be updated to work in linear space. There is also the issue of low frequency noise I'm not sure how to account for.

![psd](https://user-images.githubusercontent.com/34786005/101436825-c46a2180-38c3-11eb-946e-6e5fb89c35a8.png)

Aperiodic Removed Spectra:
![psd_flat](https://user-images.githubusercontent.com/34786005/101436701-87059400-38c3-11eb-8fff-1a7fc45eb91a.png)

**Comment by TomDonoghue** [comment]
This is perhaps more of a Development issue (https://github.com/fooof-tools/Development/) for an algorithm question / broader update / new thing (rather than a current code issue). I thought there was already an issue on this topic there (seems there might not be), but anyways, I have various notes on this as well that we can pull together to explore / set out what to do on this.
