### ISSUE TITLE
plot_fm fails when no peaks were detected

### ISSUE THREAD

**Issue by ctrltz** [fooof-tools/fooof#223]
**Issue description**

When no peaks were detected during fit, `plot_fm` function fails to plot the model fit when `plot_peaks` is set to any option but `None`.

**Code snippet**

```
import numpy as np

from fooof import FOOOF
from fooof.plts.fm import plot_fm
from fooof.sim.gen import gen_power_spectrum

freqs1, powers1 = gen_power_spectrum([3, 40], [1, 1],
                                     [[10, 0.05, 1.25]], nlv=0.02)

fm1 = FOOOF(min_peak_height=0.5, verbose=False)
fm1.fit(freqs1, powers1)

# Assert that no peaks were detected
assert(not np.count_nonzero(fm1.peak_params_))

plot_fm(fm1, plot_peaks='shade')
```

**Actual outcome**

```
TypeError: gaussian_function() argument after * must be an iterable, not numpy.float64
```

**Expected outcome**

Model fit should be plotted without any peaks.

**Comment by TomDonoghue** [comment]
Hey @ctrltz - thanks for super clean bug report - the code examples makes it much easier to check this. 

This sounded familiar, and I checked that I can replicate this on the latest release, but also that it is now fixed in main. Can you double check that if you install from Github:main that this now works for you? If so, I would recommend using the main branch for now - we will have a new proper release that includes this fix soon!

**Comment by ctrltz** [comment]
Hi Tom, thanks for the quick reply. 

Indeed, the problem is not present anymore when I use the development version, so I close the issue.
