### ISSUE TITLE
plot_spectrum

### ISSUE THREAD

**Issue by guoyongjian111** [fooof-tools/fooof#225]
plot_spectrum can not show a figure 
what i used is demo code 
from fooof import FOOOF
from fooof.sim.gen import gen_power_spectrum
from fooof.sim.utils import set_random_seed
from fooof.plts.spectra import plot_spectrum
from fooof.plts.annotate import plot_annotated_model
set_random_seed(21)

# Simulate example power spectra
freqs1, powers1 = gen_power_spectrum([3, 40], [1, 1],
                                     [[10, 0.2, 1.25], [30, 0.15, 2]])
freqs2, powers2 = gen_power_spectrum([1, 150], [1, 125, 1.25],
                                     [[8, 0.15, 1.], [30, 0.1, 2]])
fm1 = FOOOF(min_peak_height=0.05, verbose=False)
fm2 = FOOOF(min_peak_height=0.05, aperiodic_mode='knee', verbose=False)
fm1.fit(freqs1, powers1)
fm2.fit(freqs2, powers2)
plot_spectrum(freqs1, powers1, log_powers=True,color='black', label='Original Spectrum')

**Comment by TomDonoghue** [comment]
Hey @guoyongjian111 - where are you running this code, for example, in a Jupyter notebook, in iPython, in a terminal?

I double checked this code, and the figure was displayed, as expected (in a Jupyter notebook). In some cases (for example, in iPython or a terminal), you will probably have to run `plt.show()` after the code, in order to display the plot. Can you try that?

**Comment by guoyongjian111** [comment]
> 

ok,when i run plt.show() ,question was solved,thank you very much ,I'm a novice，i am so stupid... thank you!

**Comment by TomDonoghue** [comment]
@guoyongjian111 - glad you solved it!
