### ISSUE TITLE
Inconsistency between algorithm and code

### ISSUE THREAD

**Issue by rcassani** [fooof-tools/fooof#230]
Hi, 

There seems to be an inconsistency between algorithm and code.
In the algorithm (https://www.nature.com/articles/s41593-020-00744-x.pdf#page=12), it's mentioned that 
> This fit is then subtracted from the original PSD, creating a flattened spectrum, from which a power threshold (set at the **2.5 percentile**) is used to find the lowest-power points among the residuals, such that this excludes any portion of the PSD with peaks that have high-power values in the flattened spectrum

However, in the code, this is set to the 0.025 ([L171](https://github.com/fooof-tools/fooof/blob/14d6196e0b60c7e6da95b5cf858b20adcc5fc0ac/fooof/objs/fit.py#L171)), but `np.percentile` takes values in the range 0-100 (https://numpy.org/doc/stable/reference/generated/numpy.percentile.html). 

I ran few tests, and in all of them more than 2.5% of the elements flatspec are set to 0
Thus: 2.5th_percentile == 0.025th_percentile == 0
Although, I'm not sure how consistent this behaviour is

CC @lucwilson

**Comment by TomDonoghue** [comment]
Hey @rcassani - good catch, there is a bit of quirk here.

This thresholding is done in the initial aperiodic fit (`_robust_ap_fit`) in order to get started with the model fitting. Note that this sub-function is basically a heuristic fit, to get started with the model fitting - it’s not the final aperiodic fit used in the model. Both the things you ask about are things done to try and get an estimate of the aperiodic component that isn’t overly biased by any peaks. 

In that context, I'd say the exact percentile value doesn’t matter all that much, other than being relatively low to extract a set of “low" points (that are unlikely to be peaks). I think you are correct about the value being misstated, due a bad conversion between percentiles / decimals. This is arguably an issue of the value stated in the paper - I would use the value in the code (as it’s always been this value in practice, and this is what the method is tested on, etc). 

Note that this threshold value is not made explicitly public in the code, but it is settable - so you can explore variations in this value by, for example, by initializing the model like:
```
fm = FOOOF()
fm._ap_percentile_thresh = 0.05
# Then fit from here / compare to other values, etc
```

To my memory, changing this value, even fairly extremely, doesn't really do much to influence the final solutions, so I don't think this necessarily really matters that much (though if you notice anything different, please let us know).

**Comment by rcassani** [comment]
Hi @TomDonoghue, thanks for the detailed reply. 
Indeed the difference in this value does not seem to have any effect on the fit.
For sake of consistency, I'll continue using it as 0.025
