### ISSUE TITLE
Q: Gaussian error-bar

### ISSUE THREAD

**Issue by reihanehk** [fooof-tools/fooof#238]
Dear all,

I want to check the goodness of fitting of each Gaussian fit separately (for example, if a dataset has 4 peaks, I need 4 error bars). I can use pointwise_error and then extract the error of CF from it, but surely it is not sufficient. I need to have the error-bar of each Gaussian fit, not just a point. Is it possible to have it? 

Bests,
Reihaneh

**Comment by reihanehk** [comment]
Dear Tom,
Thanks for the reply. You are right. About the overlapping Gaussian, I was thinking of using the fit closer to the data to find the difference.

Do you offer any other method to calculate the error of Gaussian fit (Or CF) (not necessary pointwise difference)?

**Comment by TomDonoghue** [comment]
Hey @reihanehk - sorry for dropping off on this thread. 

In this toolbox, we don't have anything available to compute the error per peak, and as mentioned above, due to the overlapping peaks, I don't really know how this would be best addressed. 

Perhaps of interest is the error metrics that can be computed across frequencies:
https://fooof-tools.github.io/fooof/auto_examples/manage/plot_freq_by_freq_error.html

If you figured out a strategy for addressing this question, I'd be curious to hear about it!

**Comment by TomDonoghue** [comment]
Since there is not a practical to do here (at least for now), I'm going to close this. 

Note that this question is related to a broader development idea that is listed and discussed here:
https://github.com/fooof-tools/Development/issues/5
