### ISSUE TITLE
Forcing Fooof to always choose the 1st value of power spectrum as offset

### ISSUE THREAD

**Issue by csaba-a** [fooof-tools/fooof#260]
Hello,

I was wondering if you could let me know how i could force Fooof to always choose the 1st value of power spectrum as offset?
I am trying to normalize the models  across channels. 

Thanks so much!

**Comment by TomDonoghue** [comment]
Hey @csaba-a - sorry for the delay in getting back to you on this. 

I'm not sure I really understand why you are trying to do this (in terms of how it helps normalize across channels), and in general I don't think I would recommend trying to do this (in that the best model fit of the data is presumably to let the model discover the best offset value). 

That said, if you would like to try and force the model to do something like this, you can explore doing so by setting the bounds for the aperiodic parameters. See here in the code:
https://github.com/fooof-tools/fooof/blob/main/fooof/objs/fit.py#L178

For a code example, you can explore settings the bounds something like this
```
from fooof import FOOOF
fm = FOOOF()
# Set bounds on aperiodic parameters - the first element is offset (first set are mins / second are maxes)
fm._ap_bounds = ((0.0, -np.inf, -np.inf), (1.0, np.inf, np.inf))
```

In the above example, I set a bound of fitting the offset between [0, 1]. You could do something similar to this to set the bounds to reflect the lowest power value of the spectrum or similar. Note that if you do try this, definitely keep an eye on how well your models are fitting (because this might mess it up).

**Comment by TomDonoghue** [comment]
Hey @csaba-a - since there isn't an action item here, and the above hopefully answers the question, I'm going to close this issue now - but feel free to follow up if you have any comments / further questions!
