### ISSUE TITLE
Top of the Specpram 2.0.0rc2 documentation  page not adjusting properly

### ISSUE THREAD

**Issue by danieltomasz** [fooof-tools/fooof#323]
Thanks for providing new documentation page for specparam 2.0rc
https://specparam-tools.github.io/
![image](https://github.com/fooof-tools/fooof/assets/7980381/143bb68e-8518-43ef-96fe-0029b023ffc7)

There are several  small  regression that might need a fix - search window is 1 line below even when making the page width enough (fooof doc page works better adjusting in wide window)
![image](https://github.com/fooof-tools/fooof/assets/7980381/2586f9bc-858c-4d63-babc-db920204cbd5)

Separate idea - would be great to have dictionary between `fooof` and `specparam` functions, sometimes is not so easy to find new name :)

**Comment by danieltomasz** [comment]
it is possible that `2.0.0rc` just take more space and together with other menu is just wider than the maximal width of the page

**Comment by TomDonoghue** [comment]
This is now fixed!

Quick notes on the the fix (for posterity):
- I followed the instructions to add custom CSS from the theme here:
    - https://github.com/ryan-roemer/sphinx-bootstrap-theme?tab=readme-ov-file#adding-custom-css
- The relevant CSS tag is `.navbar-form.margin-right` (which @voytek figured out - thanks Brad!)

**Comment by TomDonoghue** [comment]
@danieltomasz - I've updated the changelog to now include a proper overview of the changes in 2.0 (that I'll continue to update), and updated this on the specparam docsite, which you can see here:
https://specparam-tools.github.io/changelog.html

Since this issue is now addressed (in terms of the original issue), I'm going to close this now - but feel free to follow up (here or elsewhere) on other thoughts / topics on the 2.0 version, including the list of name updates, etc.

**Comment by danieltomasz** [comment]
Great!  One thing I noticed -   by `FOOOF.modeled_spectrum_`  here https://arc.net/l/quote/fbgltigp you probably mean `Spectral` one :)

**Comment by TomDonoghue** [comment]
Ooops, good catch! Fixed that in the changelog - it'll be updated on the site next time I push an update!
