### ISSUE TITLE
include a folder for "test" data

### ISSUE THREAD

**Issue by rdgao** [fooof-tools/fooof#41]
would it be useful to have a collection of test PSDs from different recording modalities (LFP, ECoG, EEG, MEG, etc), not for any quantitative analysis of fooof, but for quick eyeballing that it still fits something reasonable for all the possible test cases when trying new algorithms?

**Comment by TomDonoghue** [comment]
So, we moved away from using real data in the test suite. There is still some in the tutorials. 

Overall, this is not something I currently envision adding to the core FOOOF repository. I can imagine maybe having a 'data examples' repository on the organization that does something similar to this idea though, which might become more relevant at some future point if we or someone else explores different fit functions or different algorithms entirely. 

That's more a development idea though - so unless someone wants to argue that we still want to do this, here in this repo, then I think I'll close this issue here.
