### ISSUE TITLE
Consistent language and variable names across code and tutorials

### ISSUE THREAD

**Issue by voytek** [fooof-tools/fooof#77]
In the paper we update the variable names such that knee is "k", broadband offset is "b", and so on. We need to update the code where needed, to reflect this.

Similarly, we've taken the stance that it should be "aperiodic signal" rather than "1/f (noise)" or "background". We need to update the code and tutorials to reflect this.

I've gone ahead and taken a first-pass stab in the tutorials, but some of the underlying plotting code, etc needs to be updated, as does the codebase.

This, of course, flies in the face of the name of the damned algorithm. We've got three things in the FOOOF name:

1. Fitting
2. Oscillations
3. One-over-f

And while we can agree we're still "fitting", we're now moving away from both "oscillations" and "1/f".
We're 2/3 wrong now 😆

**Comment by TomDonoghue** [comment]
It's sort of too late to change the code - the API was set, as we discussed and settled on, with the 0.1.0 release, and now that people have installations, it would be a nightmare to change things up and have to deal with that, across versions etc, and we would break a bunch of code (including our own). 

Our best bet to change the code is with a non-compatible 0.2.0 release, whenever that is.

**Comment by parenthetical-e** [comment]
I'd just call the next release 1.0 and promise to freeze the API from now on. 

I think it is much much better to do 1.0 ASAP and break now. The use base can only grow!


(e)

**Comment by TomDonoghue** [comment]
Note: update the description in the README as well.

**Comment by TomDonoghue** [comment]
Okay - so I'm doing the run through of the README & tutorials now, updating things a little for the moment, so that's there's a middle ground between code & paper. 

So, the main naming update is background -> aperiodic right? Is there anything else? [Other than 'fooof' itself. That's sort of grandfathered in right now, but doesn't really effect the rest of the code]. 

If it's just the background term, here is the updates that needs:
User facing updates (parameters):
	background_mode 		-> 	aperiodic_mode
	background_params_  	        -> 	aperiodic_params_

Plotting / reporting to switch:
	Reports: switch reference of background -> aperiodic in printed report
	Plots: switch reference of background -> aperiodic in legend
	Check Settings: switch reference of background -> aperiodic in printed settings
	
Internals to switch (parameters):
	_bg_fit 			        -> 	_ap_fit
	_bg_amp_thresh		-> 	_ap_amp_thresh
	_bg_guess 			-> 	_ap_guess
	_bg_bounds 			-> 	_ap_bounds

Internals to switch (methods):
	_simple_bg_fit 		-> 	_simple_ap_fit
	_robust_bg_fit 		-> 	_robust_bg_fit
	synth/gen_background -> 	synth/gen_aperiodic

Possible a couple more internals, for full consistency, and some comments and so on, but that above I think captures the thrust of it. 

So here's the options, as I see them:
- Do a quick update  and release now-ish (0.3?). It's annoying, but get's it out of the way. At a guess, people probably aren't exploring background mode all that much, so it *might* not be so bad, with the idea being get this out of the way asap. 
- Plan for these naming updates to go into a 1.0 release to be timed with the proper release of the paper. That gives us more time to find / hear about / collect any other quirks / issues (such as the bg_guess thing), collect them all together and do one major revision & breaking update.

I'm actually not sure what's best: there's a benefit to going soon, but if other things end up changing a bit through the review process as well, we don't want to potentially have a series of updates, as opposed to waiting a bit and grouping them.

**Comment by parenthetical-e** [comment]
My pennies: 

I'd go now and maybe break again later, if necessary. In either case add a clear note at the top of the readme that breaking changes are expected until 1.0, after that a hard freeze. 


(e)

**Comment by TomDonoghue** [comment]
Note: also scrub the word 'slope', in exchange for 'exponent'.

**Comment by TomDonoghue** [comment]
This was done / merged with #122
